### ISSUE TITLE
Follow Gitmoji

### ISSUE THREAD

**Issue by blfpd** [LinusU/emoji-commit#11]
Extend the list with the one listed in the gitmoji website:

https://gitmoji.carloscuesta.me/

**Comment by LinusU** [comment]
I've seen that one, and it's quite funny. But the goal of this project is to tag commits with a corresponding semver bump level.

I don't think it makes sense to tie each of those emojis to a bump level since some of them would be ambiguous. It also won't be as easy to see at a glance which kind of bump a commit would result in. 

I actually even want to remove 🔥, since it's the same as 🐛...

**Comment by blfpd** [comment]
Oh I see.
You can close it then.

**Comment by LinusU** [comment]
Cool 👌
